source: # from where i need to take the dump
  host: ""
  port: 3306
  user: ""
  password: ""
  database: ""
  ssh:
    host: ""
    port: 22
    user: "ubuntu"
    key_path: "~/.ssh/id_rsa" # prefrered
    

destination: # where i need to de-dump it
  host: ""
  port: 3306
  user: ""
  password: ""
  database: ""
  ssh:
    host: ""
    port: 22
    user: "ubuntu"
    key_path: "~/.ssh/id_rsa" 